In [164]:
import pandas as pd
import matplotlib as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [165]:
df = pd.read_csv('data.csv')

In [166]:
df.head()

,Unnamed: 0,race/ethnicity,parental level of education,lunch,test preparation course,math percentage,reading score percentage,writing score percentage,sex
0,0,group B,bachelor's degree,standard,none,0.72,0.72,0.74,F
1,1,group C,some college,standard,completed,0.69,0.90,0.88,F
2,2,group B,master's degree,standard,none,0.90,0.95,0.93,F
3,3,group A,associate's degree,free/reduced,none,0.47,0.57,0.44,M
4,4,group C,some college,standard,none,0.76,0.78,0.75,M

In [167]:
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

,race/ethnicity,parental level of education,lunch,test preparation course,math percentage,reading score percentage,writing score percentage,sex
0,group B,bachelor's degree,standard,none,0.72,0.72,0.74,F
1,group C,some college,standard,completed,0.69,0.90,0.88,F
2,group B,master's degree,standard,none,0.90,0.95,0.93,F
3,group A,associate's degree,free/reduced,none,0.47,0.57,0.44,M
4,group C,some college,standard,none,0.76,0.78,0.75,M

In [168]:
df['race/ethnicity'] = df['race/ethnicity'].map({'group A': 0, 'group B': 1, 'group C': 2, 'group D': 3, 'group E': 4})
df['race/ethnicity'].unique()

array([1, 2, 0, 3, 4], dtype=int64)

In [169]:
df['parental level of education'] = df['parental level of education'].map({'some high school': 0, 'high school': 1, 'some college': 2, "associate's degree": 3, "bachelor's degree": 4, "master's degree": 5})
df['parental level of education'].unique()

array([4, 2, 5, 3, 1, 0], dtype=int64)

In [170]:
df['lunch'] = df['lunch'].map({'free/reduced': 0, 'standard': 1})
df['lunch'].unique()

array([1, 0], dtype=int64)

In [171]:
df['test preparation course'] = df['test preparation course'].map({'none': 0, 'completed': 1})
df['test preparation course'].unique()

array([0, 1], dtype=int64)

In [172]:
df['sex'] = df['sex'].map({'M': 0, 'F': 1})

In [173]:
df.describe()

,race/ethnicity,parental level of education,lunch,test preparation course,math percentage,reading score percentage,writing score percentage,sex
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2.174000,2.081000,0.645000,0.358000,0.660890,0.691690,0.680540,0.518000
std,1.157179,1.460333,0.478753,0.479652,0.151631,0.146002,0.151957,0.499926
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.170000,0.100000,0.000000
25%,1.000000,1.000000,0.000000,0.000000,0.570000,0.590000,0.577500,0.000000
50%,2.000000,2.000000,1.000000,0.000000,0.660000,0.700000,0.690000,1.000000
75%,3.000000,3.000000,1.000000,1.000000,0.770000,0.790000,0.790000,1.000000
max,4.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [174]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [175]:
k_neighbours = KNeighborsRegressor()
linear = LinearRegression()

In [186]:
data_x = df[['reading score percentage', 'writing score percentage', 'lunch']]
data_y = df['math percentage']

In [187]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, test_size=0.1)

In [188]:
linear.fit(train_x,train_y)

LinearRegression()

In [189]:
print(f'Score Linear reg: {round(linear.score(test_x, test_y), 10) * 100}%')

Score Linear reg: 69.05084424%