In [140]:
# Importamos las librerias necesarias
from sklearn.model_selection import train_test_split
from sklearn import linear_model

import pandas as pd

In [141]:
# Importamos el dataset para manejarlo como un Dataframe
df = pd.read_csv('sloth_data.csv')

In [142]:
df.sample(frac=0.65)

,id,claw_length_cm,endangered,size_cm,specie,sub_specie,tail_length_cm,weight_kg
3280,3280,8.605,least_concern,65.066,two_toed,Linnaeus’s two-toed sloth,-0.364,8.469
3446,3446,8.685,least_concern,65.848,two_toed,Linnaeus’s two-toed sloth,-0.342,5.936
1636,1636,9.655,least_concern,51.173,three_toed,Pale-throated sloth,5.437,4.479
3091,3091,9.320,least_concern,66.666,two_toed,Linnaeus’s two-toed sloth,0.162,4.849
3421,3421,6.677,least_concern,64.986,two_toed,Linnaeus’s two-toed sloth,0.184,5.286
...,...,...,...,...,...,...,...,...
1992,1992,7.574,least_concern,60.244,three_toed,Brown-throated sloth,6.502,4.053
538,538,8.779,vulnerable,61.617,three_toed,Maned three-toed sloth,4.856,7.096
637,637,6.540,least_concern,50.355,three_toed,Pale-throated sloth,4.845,4.823
3456,3456,7.910,least_concern,67.089,two_toed,Linnaeus’s two-toed sloth,-0.337,5.791
4889,4889,4.358,least_concern,62.312,two_toed,Hoffman’s two-toed sloth,3.658,5.471

In [143]:
# Famaliarizarse con el dataframe luego hacer la limpieza de datos
df.specie.unique()
df.specie = df.specie.map({'three_toed': 0, 'two_toed': 1})

In [144]:
df.sub_specie.unique()
df.sub_specie = df.sub_specie.map({'Pygmy three-toed sloth': 0, 'Maned three-toed sloth': 1,
       'Pale-throated sloth': 2, 'Brown-throated sloth': 3,
       'Linnaeus’s two-toed sloth': 4, 'Hoffman’s two-toed sloth': 5})

In [145]:
df.endangered.unique()
df.endangered = df.endangered.map({'critically_endangered': 0, 'vulnerable': 1, 'least_concern': 2})

In [146]:
df.describe()

,id,claw_length_cm,endangered,size_cm,specie,sub_specie,tail_length_cm,weight_kg
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2499.500000,7.423503,1.863400,60.399852,0.467600,3.238600,3.410544,5.253253
std,1443.520003,1.520533,0.383627,5.929968,0.498999,1.378713,2.333288,1.268203
min,0.000000,1.748000,0.000000,46.928000,0.000000,0.000000,-2.942000,0.946000
25%,1249.750000,6.383750,2.000000,59.904750,0.000000,2.000000,1.440250,4.382500
50%,2499.500000,7.445000,2.000000,62.478500,0.000000,3.000000,3.812000,5.274000
75%,3749.250000,8.491500,2.000000,64.398250,1.000000,4.000000,5.351250,6.125250
max,4999.000000,12.171000,2.000000,68.760000,1.000000,5.000000,8.538000,9.997000

In [147]:
# Analisis de correlacion
corr = df.corr()
corr.style.background_gradient()

In [148]:
# Inicializamos el modelo
linear = linear_model.LinearRegression()

In [166]:
# Escogemos sub_specie como variable dependiente y el resto como independientes porque son las que tienen mayor correlacion
data_x = df.drop(['claw_length_cm', 'tail_length_cm', 'sub_specie', 'weight_kg', 'size_cm'], axis=1)
data_y = df.sub_specie

In [167]:
data_x

        id  endangered  specie
0        0           0       0
1        1           0       0
2        2           0       0
3        3           0       0
4        4           0       0
...    ...         ...     ...
4995  4995           2       1
4996  4996           2       1
4997  4997           2       1
4998  4998           2       1
4999  4999           2       1

[5000 rows x 3 columns]

In [168]:
data_y

0       0
1       0
2       0
3       0
4       0
       ..
4995    5
4996    5
4997    5
4998    5
4999    5
Name: sub_specie, Length: 5000, dtype: int64

In [169]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y)

In [170]:
# Entrenamos el modelo
linear.fit(train_x, train_y)

LinearRegression()

In [171]:
# Ecuacion de la recta
print(f'y = {round( linear.coef_[0], 2)}x + {round(linear.intercept_, 2)}')

y = 0.0x + 0.09

In [172]:
# Veamos la calificacion
print(f'Score: {round(linear.score(test_x, test_y), 4) * 100}%')

Score: 97.08%

In [179]:
# Vamos a predecir y dar formato al resultado
id = 10
specie = 0
endangered = 0
labels1 = {0: 'Pygmy three-toed sloth', 1: 'Maned three-toed sloth',
       2: 'Pale-throated sloth', 3: 'Brown-throated sloth',
       4: 'Linnaeus’s two-toed sloth', 5: 'Hoffman’s two-toed sloth'}
labels2 = {0: 'critically_endangered', 1: 'vulnerable', 2: 'least_concern'}
predict = linear.predict([[id, specie, endangered]])
print(f'La sub especie con id: {id}, es: {labels1[int(round(predict[0], 0))]} y su estado de conservacion es: {labels2[endangered]}')

La sub especie con id: 10, es: Pygmy three-toed sloth y su estado de conservacion es: critically_endangered

c:\Users\Sebastian\OneDrive\Documentos\Algorimitca\Practico2\linear_regresion_env\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(