In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('covid.csv')

In [ ]:
df.shape

(1048575, 21)

In [ ]:
df.isnull().sum()

USMER                   0
MEDICAL_UNIT            0
SEX                     0
PATIENT_TYPE            0
DATE_DIED               0
INTUBED                 0
PNEUMONIA               0
AGE                     0
PREGNANT                0
DIABETES                0
COPD                    0
ASTHMA                  0
INMSUPR                 0
HIPERTENSION            0
OTHER_DISEASE           0
CARDIOVASCULAR          0
OBESITY                 0
RENAL_CHRONIC           0
TOBACCO                 0
CLASIFFICATION_FINAL    0
ICU                     0
dtype: int64

In [ ]:
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [ ]:
for i in df.columns:
    print(i,"=>\t",len(df[i].unique()))

USMER =>	 2
MEDICAL_UNIT =>	 13
SEX =>	 2
PATIENT_TYPE =>	 2
DATE_DIED =>	 401
INTUBED =>	 4
PNEUMONIA =>	 3
AGE =>	 121
PREGNANT =>	 4
DIABETES =>	 3
COPD =>	 3
ASTHMA =>	 3
INMSUPR =>	 3
HIPERTENSION =>	 3
OTHER_DISEASE =>	 3
CARDIOVASCULAR =>	 3
OBESITY =>	 3
RENAL_CHRONIC =>	 3
TOBACCO =>	 3
CLASIFFICATION_FINAL =>	 7
ICU =>	 4

In [ ]:
df = df[(df.PNEUMONIA == 1) | (df.PNEUMONIA == 2)]
df = df[(df.DIABETES == 1) | (df.DIABETES == 2)]
df = df[(df.COPD == 1) | (df.COPD == 2)]
df = df[(df.ASTHMA == 1) | (df.ASTHMA == 2)]
df = df[(df.INMSUPR == 1) | (df.INMSUPR == 2)]
df = df[(df.HIPERTENSION == 1) | (df.HIPERTENSION == 2)]
df = df[(df.OTHER_DISEASE == 1) | (df.OTHER_DISEASE == 2)]
df = df[(df.CARDIOVASCULAR == 1) | (df.CARDIOVASCULAR == 2)]
df = df[(df.OBESITY == 1) | (df.OBESITY == 2)]
df = df[(df.RENAL_CHRONIC == 1) | (df.RENAL_CHRONIC == 2)]
df = df[(df.TOBACCO == 1) | (df.TOBACCO == 2)]
df.PREGNANT = df.PREGNANT.replace(97,2)
df = df[(df.PREGNANT == 1) | (df.PREGNANT == 2)]
df["DEATH"] = [2 if each=="9999-99-99" else 1 for each in df.DATE_DIED]

In [ ]:
df.drop(columns=["INTUBED","ICU","DATE_DIED"], inplace=True)
#Muchos valores nulos

In [ ]:
for i in df.columns:
    print(i,"=>\t",len(df[i].unique()))

USMER =>	 2
MEDICAL_UNIT =>	 13
SEX =>	 2
PATIENT_TYPE =>	 2
PNEUMONIA =>	 2
AGE =>	 121
PREGNANT =>	 2
DIABETES =>	 2
COPD =>	 2
ASTHMA =>	 2
INMSUPR =>	 2
HIPERTENSION =>	 2
OTHER_DISEASE =>	 2
CARDIOVASCULAR =>	 2
OBESITY =>	 2
RENAL_CHRONIC =>	 2
TOBACCO =>	 2
CLASIFFICATION_FINAL =>	 7
DEATH =>	 2

In [ ]:
from sklearn.model_selection import train_test_split

x = df.drop('DEATH', axis=1)
y = df['DEATH']

df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,DEATH
0,2,1,1,1,1,65,2,2,2,2,2,1,2,2,2,2,2,3,1
1,2,1,2,1,1,72,2,2,2,2,2,1,2,2,1,1,2,5,1
2,2,1,2,2,2,55,2,1,2,2,2,2,2,2,2,2,2,3,1
3,2,1,1,1,2,53,2,2,2,2,2,2,2,2,2,2,2,7,1
4,2,1,2,1,2,68,2,1,2,2,2,1,2,2,2,2,2,3,1

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((817581, 18), (204396, 18), (817581,), (204396,))

In [ ]:
x_train.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL
927774,2,12,1,1,2,67,2,2,2,2,2,1,2,1,2,2,2,7
233768,2,4,1,1,2,26,2,2,2,2,2,2,2,2,2,2,2,7
285741,1,4,2,1,2,23,2,2,2,2,2,2,2,2,1,2,1,7
838534,2,12,1,1,2,36,2,2,2,2,2,2,2,2,2,2,2,7
304839,2,4,1,1,2,37,2,2,2,2,2,2,2,2,2,2,2,7

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
x_train_scaled[:3]

array([[ 0.74702807,  0.80853609, -1.00235238, -0.48081361,  0.39415479,
         1.4983441 ,  0.08779726,  0.36912322,  0.11950062,  0.17477938,
         0.11549917, -2.32647815,  0.16484462, -7.0509062 ,  0.42560249,
         0.1353063 ,  0.29665801,  0.9047704 ],
       [ 0.74702807, -1.33956065, -1.00235238, -0.48081361,  0.39415479,
        -0.94903541,  0.08779726,  0.36912322,  0.11950062,  0.17477938,
         0.11549917,  0.42983425,  0.16484462,  0.14182574,  0.42560249,
         0.1353063 ,  0.29665801,  0.9047704 ],
       [-1.33863778, -1.33956065,  0.99765314, -0.48081361,  0.39415479,
        -1.12811196,  0.08779726,  0.36912322,  0.11950062,  0.17477938,
         0.11549917,  0.42983425,  0.16484462,  0.14182574, -2.34961032,
         0.1353063 , -3.37088493,  0.9047704 ]])

In [ ]:
import tensorflow as tf

tf.random.set_seed(42)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss=tf.keras.losses.binary_crossentropy,
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.03),
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name='accuracy'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')
    ]
)

WARNING:tensorflow:Keras is training/fitting/evaluating on array-like data. Keras may not be optimized for this format, so if your input data format is supported by TensorFlow I/O (https://github.com/tensorflow/io) we recommend using that to load a Dataset instead.

WARNING:tensorflow:Keras is training/fitting/evaluating on array-like data. Keras may not be optimized for this format, so if your input data format is supported by TensorFlow I/O (https://github.com/tensorflow/io) we recommend using that to load a Dataset instead.

Epoch 1/100

UnknownError: Graph execution error:

KeyError: '[31823, 577583, 629831, 539094, 734022, 463961, 648866, 450628, 12611] not in index'
Traceback (most recent call last):

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\tensorflow\python\ops\script_ops.py", line 266, in __call__
    return func(device, token, args)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\tensorflow\python\ops\script_ops.py", line 144, in __call__
    outputs = self._call(device, args)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\tensorflow\python\ops\script_ops.py", line 151, in _call
    ret = self._func(*args)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 643, in wrapper
    return func(*args, **kwargs)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\engine\data_adapter.py", line 519, in py_method
    return [slice_array(inp) for inp in flat_inputs]

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\engine\data_adapter.py", line 519, in <listcomp>
    return [slice_array(inp) for inp in flat_inputs]

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\engine\data_adapter.py", line 515, in slice_array
    return training_utils.slice_arrays(

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\engine\training_utils.py", line 52, in slice_arrays
    slices = generic_utils.slice_arrays(arrays, indices)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\utils\generic_utils.py", line 444, in slice_arrays
    return [None if x is None else x[start] for x in arrays]

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\keras\src\utils\generic_utils.py", line 444, in <listcomp>
    return [None if x is None else x[start] for x in arrays]

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\series.py", line 1033, in __getitem__
    return self._get_with(key)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\series.py", line 1068, in _get_with
    return self.loc[key]

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexing.py", line 1103, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexing.py", line 1332, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexing.py", line 1272, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexing.py", line 1462, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexes\base.py", line 5877, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)

  File "c:\Users\Ronal\Desktop\xdt\venv\lib\site-packages\pandas\core\indexes\base.py", line 5941, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")

KeyError: '[31823, 577583, 629831, 539094, 734022, 463961, 648866, 450628, 12611] not in index'


	 [[{{node EagerPyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_42430]

In [ ]:
history = model.fit(x_train_scaled, y_train, epochs=100)